import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{supabase}from'./supabase';
import{signIn,signOut,signUp,getCurrentProfile}from'./auth';
import{getQuestions,getPortfolios,createAssessment,getMySuitability,recordInvestmentConsent,submitInvestment,getMyRequests,getMyTransactions,getMyStatements,saveSimulation,getAdminData,upsertAsset,upsertPortfolioVersion,getMyValuations,getMyDocuments,getMyNotifications,markNotificationRead,deleteAsset,upsertCorporateAction,setCorporateActionStatus,deleteCorporateAction}from'./data';
import{preferenceScore,riskBand,needsConsent,RiskBand}from'./risk';
import{project}from'./monteCarlo';
import'./styles.css';

type Profile={id:string;display_name:string;role:string};
type SessionState={user:any;profile:Profile}|null;
type Version=any;

const labels:Record<string,string>={Conservative:'Conservative',Balanced:'Balanced',Aggressive:'Aggressive'};
const tag=(band:string)=>band==='Conservative'?'tag-conservative':band==='Aggressive'?'tag-aggressive': 'tag-balanced';

function Auth({onDone}:{onDone:(s:SessionState)=>void}){
 const[mode,setMode]=useState<'signIn'|'signUp'>('signIn'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setLoading(true);try{const data=mode==='signIn'?await signIn(email,password):await signUp(email,password,name);if(mode==='signUp'&&!data.session){setError('Account created. Check your email to confirm the account.');return}onDone(await getCurrentProfile())}catch(err:any){setError(err.message||'Authentication failed')}finally{setLoading(false)}}
 return <div className="auth-shell"><div className="auth-card"><div className="brandmark"><span className="mark">EmCoin</span><span className="sub">Guided Portfolios</span></div><p className="eyebrow">Investor Access</p><h1 className="title">{mode==='signIn'?'Welcome back':'Create your investor account'}</h1><form onSubmit={submit}>{mode==='signUp'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/><button className="btn btn-primary" disabled={loading}>{loading?'Please wait...':mode==='signIn'?'Sign in':'Create account'}</button></form>{error&&<div className="notice">{error}</div>}<button className="link" onClick={()=>setMode(mode==='signIn'?'signUp':'signIn')}>{mode==='signIn'?'Create a new account':'I already have an account'}</button></div></div>
}

function PortfolioCard({v,recommended,approved,onSelect}:{v:Version;recommended:boolean;approved:RiskBand;onSelect:(v:Version)=>void}){
 const diff=(v.risk_score??0)-({Conservative:1,Balanced:2,Aggressive:5}[approved]??2);
 const deviation=Math.abs(diff);
 const deviationClass=diff<=0?'ok':diff===1?'warn':'danger';
 return <div className={'pf-card '+(recommended?'recommended ':'')+(diff>0?'deviation-'+Math.min(diff,2):'')} onClick={()=>onSelect(v)}>
   {recommended&&<span className="reco-badge">★ Recommended</span>}
   <span className={'pf-tag '+tag(v.band)}>{v.band}</span>
   <div className="pf-name">{v.portfolioName}</div>
   <div className="pf-desc">{v.definition?.description||'Portfolio strategy and allocation details'}</div>
   <span className={'deviation-badge '+deviationClass}>{diff<=0?'Within profile':deviation===1?'One level above':'Above profile'}</span>
   <div className="pf-stats"><div className="pf-stat"><b>{(Number(v.target_return)*100).toFixed(1)}%</b><span>Target return</span></div><div className="pf-stat"><b>{(Number(v.volatility)*100).toFixed(1)}%</b><span>Volatility</span></div><div className="pf-stat"><b>{v.risk_score}/5</b><span>Risk</span></div></div>
 </div>
}

function App({session,onLogout}:{session:SessionState;onLogout:()=>void}){
 const[questions,setQuestions]=useState<any[]>([]),[answers,setAnswers]=useState<number[]>([]),[portfolios,setPortfolios]=useState<any[]>([]),[assessment,setAssessment]=useState<any>(null),[approved,setApproved]=useState<RiskBand>('Balanced'),[step,setStep]=useState(1),[selected,setSelected]=useState<Version|null>(null),[initial,setInitial]=useState(100000),[monthly,setMonthly]=useState(0),[years,setYears]=useState(10),[goal,setGoal]=useState(180000),[inflation,setInflation]=useState(false),[projection,setProjection]=useState<any[]>([]),[consents,setConsents]=useState(false),[consentId,setConsentId]=useState<string|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[requests,setRequests]=useState<any[]>([]),[transactions,setTransactions]=useState<any[]>([]),[statements,setStatements]=useState<any[]>([]);
 const isStaff=['portfolio_manager','investment_reviewer','compliance_officer','admin'].includes(session?.profile.role||'');
 useEffect(()=>{(async()=>{try{const[q,p,s,r,t,st]=await Promise.all([getQuestions(),getPortfolios(),getMySuitability(),getMyRequests(),getMyTransactions(),getMyStatements()]);setQuestions(q);setPortfolios(p);if(s)setApproved(s.approved_band);setRequests(r);setTransactions(t);setStatements(st);setValuations(await getMyValuations());setDocuments(await getMyDocuments());setNotifications(await getMyNotifications())}catch(e:any){setMessage(e.message||'Could not load data')}finally{setLoading(false)}})()},[]);
 const versions=portfolios.flatMap(p=>(p.portfolio_versions||[]).map((v:any)=>({...v,portfolioName:p.name,slug:p.slug,portfolioId:p.id})));
 const score=assessment?.score??(answers.length===5?preferenceScore(answers):null);
 const band=assessment?.band??(score===null?null:riskBand(score));
 const recommended=band?versions.find(v=>v.band===band)||versions[0]:null;
 useEffect(()=>{if(selected){setProjection(project(initial,monthly,years,Number(selected.target_return),Number(selected.volatility),42,10000))}},[selected,initial,monthly,years]);
 async function assess(){try{const a=await createAssessment(answers);setAssessment(a);setMessage('Assessment saved.');setStep(2)}catch(e:any){setMessage(e.message)}}
 async function selectPortfolio(v:Version){setSelected(v);setConsents(false);setConsentId(null);setStep(3)}
 async function continueSimulation(){if(!selected)return;setStep(4);setProjection(project(initial,monthly,years,Number(selected.target_return),Number(selected.volatility),42,10000))}
 async function confirm(){if(!selected)return;try{let cid=consentId;if(needsConsent(approved,selected.band)){if(!consents){setMessage('Please complete the additional risk consent.');return}if(!cid){const c=await recordInvestmentConsent(selected.id,'Investor acknowledged the additional risk disclosure for a selected portfolio outside the approved suitability band.');cid=c.id;setConsentId(cid)}}await saveSimulation({portfolioVersionId:selected.id,initialAmount:initial,monthlyContribution:monthly,horizonYears:years,seed:42,paths:10000,results:{projection,goal,inflation}});await submitInvestment({portfolioVersionId:selected.id,amount:initial,monthlyContribution:monthly,consentId:cid});setRequests(await getMyRequests());setStep(6);setMessage('Portfolio confirmed and investment request submitted.')}catch(e:any){setMessage(e.message)}}
 if(loading)return <div className="center">Starting Guided Portfolios...</div>;
 return <div className="app">
  <header className="topbar"><div className="brandmark"><span className="mark">EmCoin</span><span className="sub">Guided Portfolios · Monte Carlo</span></div><div className="nav-toggle"><button className={step<6?'active':''} onClick={()=>setStep(1)}>Investor View</button>{isStaff&&<button className={step===7?'active':''} onClick={()=>setStep(7)}>Admin Console</button>}</div><button className="btn btn-ghost btn-small" onClick={onLogout}>Sign out</button></header>
  <div className="cma-banner"><div className="cma-left"><div className="cma-icon">🔒</div><div className="cma-info"><h3>Your Approved Investment Profile</h3><p>Based on your CMA suitability profile maintained by EmCoin</p></div></div><div className="cma-stats"><div className="cma-stat"><b>{approved}</b><span>Risk Category</span></div><div className="cma-stat"><b>{assessment?.score??'Not assessed'}</b><span>Preference Score</span></div><div className="cma-stat"><b>Complete</b><span>Account Status</span></div></div></div>
  <div className="ledger">{['Preferences','Portfolio Selection','Portfolio Details','Monte Carlo','Confirmation','Dashboard'].map((x,i)=>{const n=i+1;return <React.Fragment key={x}><div className={'ledger-step '+(step>n?'done ':'')+(step===n?'current':'')}><div className="ledger-num">{n}</div><div className="ledger-label">{x}</div></div>{n<6&&<div className="ledger-rule"/>}</React.Fragment>})}</div>
  {message&&<div className="notice">{message}</div>}
  {step===1&&<section className="panel"><p className="eyebrow">Step 1 · Investment Preference Check</p><h1 className="title">Align with your investment goals</h1><p className="lede">These questions help us understand your preferences. Your approved CMA risk profile remains the governing suitability reference.</p><div className="qwrap">{questions.map(q=><div className="qitem" key={q.id}><div className="qhead"><div className="qtext">{q.prompt}</div></div><div className="opts">{[1,2,3,4,5].map(v=><label className={'opt '+(answers[q.position-1]===v?'selected':'')} key={v}><input type="radio" checked={answers[q.position-1]===v} onChange={()=>setAnswers(a=>{const n=[...a];n[q.position-1]=v;return n})}/>{v}</label>)}</div><div className="scale"><span>{q.min_label}</span><span>{q.max_label}</span></div></div>)}</div><div className="btnrow"><button className="btn btn-primary" disabled={answers.filter(Boolean).length!==5} onClick={assess}>See my recommendation</button></div></section>}
  {step===2&&<section className="panel"><p className="eyebrow">Step 2 · Portfolio Selection</p><h1 className="title">Choose your portfolio</h1>{recommended&&<><div className="reco-badge">★ Recommended: {recommended.portfolioName}</div><div className="score-strip"><div className="score-track"><div className="score-fill" style={{width:(score??0)+'%'}}/></div><div className="score-val">{score??0}/100</div></div><div className="why-reco"><h4>💡 Why this is recommended for you</h4><ul><li>Your preference score maps to the {band} preference band.</li><li>Your approved CMA profile is {approved}.</li><li>You can review and select any available portfolio below.</li></ul></div></>}<p className="lede">All available portfolios are shown below. The recommendation is highlighted, but it does not hide the other choices. Selecting a portfolio outside your approved risk category may require additional consent or advisor review.</p><div className="pf-grid">{versions.map(v=><PortfolioCard key={v.id} v={v} recommended={v.id===recommended?.id} approved={approved} onSelect={selectPortfolio}/>)}</div><div className="btnrow"><button className="btn btn-ghost" onClick={()=>setStep(1)}>← Back to preferences</button></div></section>}
  {step===3&&selected&&<section className="panel"><div className="details-head"><div><p className="eyebrow">{selected.band} <span className="version-badge">v{selected.version}</span></p><h1 className="title">{selected.portfolioName}</h1><p className="lede">{selected.definition?.description}</p></div><div className="metric-grid"><div className="metric-box"><b>{(Number(selected.target_return)*100).toFixed(1)}%</b><span>Target Return/yr</span></div><div className="metric-box"><b>{selected.risk_score}/5</b><span>Risk Rating</span></div><div className="metric-box"><b>{(Number(selected.volatility)*100).toFixed(1)}%</b><span>Volatility</span></div></div></div><div className="benchmark-card"><h4>📊 Benchmark</h4><div className="benchmark-row"><span className="label">Benchmark</span><span className="value">{selected.portfolio_benchmarks?.[0]?.name||'Portfolio benchmark'}</span></div></div><div className="detail-grid"><div><div className="block-title">Holdings</div>{(selected.portfolio_holdings||[]).map((h:any)=><div className="holding-row" key={h.symbol}><div><div className="holding-name">{h.name}</div><div className="holding-meta">{h.asset_class} · {h.symbol}</div></div><div className="holding-weight">{h.allocation}%</div></div>)}</div><div><div className="block-title">Asset Allocation</div>{(selected.portfolio_holdings||[]).map((h:any)=><div className="bar-row" key={h.symbol}><div className="bar-label"><span>{h.asset_class}</span><span>{h.allocation}%</span></div><div className="bar-track"><div className="bar-fill" style={{width:Math.min(100,Number(h.allocation))+'%'}}/></div></div>)}</div></div>{needsConsent(approved,selected.band)&&<div className="warn-strip">⚠️ This selection is outside your approved risk category. Additional consent is required before submission.</div>}<div className="btnrow"><button className="btn btn-ghost" onClick={()=>setStep(2)}>← Back to selection</button><button className="btn btn-primary" onClick={continueSimulation}>Continue to Monte Carlo</button></div></section>}
  {step===4&&selected&&<section className="panel"><p className="eyebrow">Step 4 · Monte Carlo Projection</p><h1 className="title">Model your investment</h1><p className="lede">We run 10,000 seeded simulations using the selected portfolio assumptions. Results are illustrative and do not guarantee future performance.</p><div className="sim-inputs"><div className="field"><label>Investment Amount (AED)</label><input type="number" value={initial} min={1000} step={1000} onChange={e=>setInitial(Number(e.target.value))}/></div><div className="field"><label>Time Horizon (Years)</label><input type="number" value={years} min={1} max={30} onChange={e=>setYears(Number(e.target.value))}/></div><div className="field"><label>Goal Amount (AED)</label><input type="number" value={goal} min={0} step={1000} onChange={e=>setGoal(Number(e.target.value))}/></div><div className="field"><label>Monthly Contribution (AED)</label><input type="number" value={monthly} min={0} step={500} onChange={e=>setMonthly(Number(e.target.value))}/></div></div><div className="toggle-row"><span className="toggle-label">Show inflation-adjusted values</span><label className="toggle-switch"><input type="checkbox" checked={inflation} onChange={e=>setInflation(e.target.checked)}/><span className="toggle-slider"/></label><span className="inflation-note">Assumed inflation rate: 2.5% per annum</span></div><div className="sim-results"><div className="mc-percentiles">{[10,50,90].map(p=>{const vals=projection.map((x:any)=>x['p'+p]).filter(Boolean);const val=vals[vals.length-1]||0;return <div className={'mc-percentile '+(p===50?'highlight':'')} key={p}><b>{Math.round(val).toLocaleString()} AED</b><span>P{p} outcome</span></div>})}</div><p className="lede">Goal: {goal.toLocaleString()} AED. Projection updates from the same deterministic seed.</p></div><div className="btnrow"><button className="btn btn-ghost" onClick={()=>setStep(3)}>← Back to details</button><button className="btn btn-primary" onClick={()=>setStep(5)}>Continue to confirmation</button></div></section>}
  {step===5&&selected&&<section className="panel"><p className="eyebrow">Step 5 · Confirmation & Consent</p><h1 className="title">Review & confirm</h1><p className="lede">This summary reflects your selections and the portfolio you chose. The recommended portfolio is not automatically enforced.</p><div className="confirm-slip"><div className="strip-head"><strong>{selected.portfolioName}</strong><span className="stamp">v{selected.version}</span></div><div className="slip-body">{[['Portfolio',selected.portfolioName],['Investment Amount',initial.toLocaleString()+' AED'],['Monthly Contribution',monthly.toLocaleString()+' AED'],['Time Horizon',years+' years'],['Target Return',(Number(selected.target_return)*100).toFixed(1)+'% / yr'],['CMA Profile',approved]].map(([k,v])=><div className="slip-row" key={k}><span className="k">{k}</span><span className="v">{v}</span></div>)}</div></div>{needsConsent(approved,selected.band)&&<div className="consent-checks"><div className={'consent-check-item '+(consents?'checked':'')}><input type="checkbox" checked={consents} onChange={e=>setConsents(e.target.checked)}/><label><b>Additional risk acknowledgement.</b> I understand this portfolio is outside my approved CMA risk category and I choose to proceed after reviewing the risk disclosure.</label></div></div>}<div className="consent-checks"><div className="consent-check-item"><input type="checkbox" defaultChecked/><label><b>I understand that capital is at risk.</b> Portfolio values can go down as well as up.</label></div><div className="consent-check-item"><input type="checkbox" defaultChecked/><label><b>I understand that projections are illustrative.</b> Monte Carlo results do not guarantee future performance.</label></div></div><div className="disclaimer-box"><strong>Important Disclosure:</strong> Portfolio projections are illustrative only. Past performance is not indicative of future results.</div><div className="btnrow"><button className="btn btn-ghost" onClick={()=>setStep(4)}>← Back</button><button className="btn btn-primary" onClick={confirm}>✓ Confirm portfolio</button><button className="btn btn-ghost" onClick={()=>setStep(2)}>Choose another portfolio</button></div></section>}
  {step===6&&selected&&<section className="panel"><div className="dash-header"><div><p className="eyebrow">My Portfolio Dashboard</p><h1 className="title">{selected.portfolioName}</h1><span className="version-badge">v{selected.version} · {selected.band}</span></div><Certificate selected={selected} initial={initial} monthly={monthly} years={years} approved={approved}/></div><div className="dash-stats"><div className="dash-stat-card"><b>{initial.toLocaleString()} AED</b><span>Total Invested</span></div><div className="dash-stat-card"><b>{monthly.toLocaleString()} AED</b><span>Monthly Contribution</span></div><div className="dash-stat-card"><b>✓ Confirmed</b><span>Portfolio Status</span></div><div className="dash-stat-card"><b>{approved}</b><span>CMA Profile</span></div></div><div className="dash-sections"><div className="dash-section"><h3>🔔 Notifications</h3>{notifications.filter((n:any)=>!n.read_at).slice(0,5).map((n:any)=><div className="notice" key={n.id} onClick={()=>markNotificationRead(n.id).then(()=>setNotifications(x=>x.map(y=>y.id===n.id?{...y,read_at:new Date().toISOString()}:y)))}><b>{n.title}</b><br/>{n.body}</div>)}{!notifications.filter((n:any)=>!n.read_at).length&&<p className="lede">No unread notifications.</p>}</div><div className="dash-section"><h3>📋 Investment Requests</h3>{requests.length?<table className="admin-table"><tbody>{requests.map(r=><tr key={r.id}><td>{r.portfolio_versions?.portfolios?.name}</td><td>{Number(r.amount).toLocaleString()} AED</td><td>{r.status}</td></tr>)}</tbody></table>:<p className="lede">No investment requests yet.</p>}</div><div className="dash-section"><h3>📊 Allocation</h3>{(selected.portfolio_holdings||[]).map((h:any)=><div className="bar-row" key={h.symbol}><div className="bar-label"><span>{h.name}</span><span>{h.allocation}%</span></div><div className="bar-track"><div className="bar-fill" style={{width:h.allocation+'%'}}/></div></div>)}</div></div><div className="btnrow"><button className="btn btn-ghost" onClick={()=>setStep(2)}>View all portfolios</button></div></section>}
  {step===7&&isStaff&&<Governance/>}
 </div>
}

function Certificate({selected,initial,monthly,years,approved}:{selected:any;initial:number;monthly:number;years:number;approved:string}){
 const printCertificate=()=>{const w=window.open('','_blank','width=900,height=700');if(!w)return;
 w.document.write('<!doctype html><html><head><title>EmCoin Investment Certificate</title><style>body{font-family:Arial,sans-serif;background:#f5f3ee;padding:50px;color:#17201d}.cert{max-width:760px;margin:auto;background:#fff;border:12px double #17201d;padding:55px;text-align:center}.brand{font-size:30px;font-weight:800;letter-spacing:2px}.small{color:#66716d;letter-spacing:2px;text-transform:uppercase}.line{height:1px;background:#d7d2c7;margin:25px}.value{font-size:28px;font-weight:800;margin:15px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;text-align:left;margin:30px 0}.cell{padding:14px;background:#f5f3ee}.footer{font-size:12px;color:#66716d;margin-top:35px}@media print{body{padding:0}.cert{border:12px double #17201d}}</style></head><body><div class="cert"><div class="brand">EmCoin</div><div class="small">Guided Portfolios</div><div class="line"></div><div class="small">Investment Portfolio Certificate</div><div class="value">${selected.portfolioName}</div><div>Portfolio version v${selected.version} · ${selected.band}</div><div class="grid"><div class="cell"><b>Investment Amount</b><br/>${initial.toLocaleString()} AED</div><div class="cell"><b>Monthly Contribution</b><br/>${monthly.toLocaleString()} AED</div><div class="cell"><b>Investment Horizon</b><br/>${years} years</div><div class="cell"><b>Approved CMA Profile</b><br/>${approved}</div></div><div>Issued by EmCoin Guided Portfolios</div><div class="footer">This certificate records the investor portfolio selection. It is not a guarantee of performance or a statement of account. Generated ${new Date().toLocaleString()}.</div></div><script>window.print();</script></body></html>');w.document.close()};
 return <div className="dash-section certificate-card"><h3>📜 Investment Certificate</h3><p className="lede">Create a print-ready certificate and choose “Save as PDF” in your browser print dialog.</p><button className="btn btn-primary" onClick={printCertificate}>Print / Save PDF Certificate</button></div>
}

function Governance(){
 const[tab,setTab]=useState('overview'); const[data,setData]=useState<any>({assets:[],actions:[],portfolios:[],requests:[],profiles:[]}); const[error,setError]=useState(''); const[busy,setBusy]=useState(false);
 const[asset,setAsset]=useState<any>({symbol:'',name:'',asset_class:'Equity',currency:'AED',exchange:'',isin:'',active:true});
 const[action,setAction]=useState<any>({asset_id:'',action_type:'dividend',announcement_date:'',ex_date:'',record_date:'',payment_date:'',ratio:'',cash_amount:'',currency:'AED',details:{}});
 const[portfolio,setPortfolio]=useState<any>({slug:'',name:'',active:true}); const[version,setVersion]=useState<any>({portfolio_id:'',version:1,band:'Balanced',target_return:.08,volatility:.1,risk_score:2,definition:{description:''}});
 const[valuation,setValuation]=useState<any>({user_id:'',portfolio_version_id:'',valuation_date:new Date().toISOString().slice(0,10),market_value:0,cash_value:0,net_contributions:0,net_withdrawals:0,unrealized_pnl:0,realized_pnl:0,time_weighted_return:'',money_weighted_return:''});
 const load=async()=>{try{setData(await getAdminData());setError('')}catch(e:any){setError(e.message||'Unable to load admin data')}}; useEffect(()=>{load()},[]);
 const saveAsset=async()=>{setBusy(true);try{await upsertAsset(asset);setAsset({symbol:'',name:'',asset_class:'Equity',currency:'AED',exchange:'',isin:'',active:true});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const saveAction=async()=>{setBusy(true);try{await upsertCorporateAction(action);setAction({asset_id:'',action_type:'dividend',announcement_date:'',ex_date:'',record_date:'',payment_date:'',ratio:'',cash_amount:'',currency:'AED',details:{}});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const savePortfolio=async()=>{setBusy(true);try{const{error}=await supabase.rpc('admin_upsert_portfolio',{p_id:portfolio.id??null,p_slug:portfolio.slug,p_name:portfolio.name,p_active:portfolio.active});if(error)throw error;setPortfolio({slug:'',name:'',active:true});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const saveVersion=async()=>{setBusy(true);try{await upsertPortfolioVersion(version);setVersion({portfolio_id:'',version:1,band:'Balanced',target_return:.08,volatility:.1,risk_score:2,definition:{description:''}});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const recordValuation=async()=>{setBusy(true);try{const{error}=await supabase.rpc('admin_record_valuation',{p_user_id:valuation.user_id,p_portfolio_version_id:valuation.portfolio_version_id,p_valuation_date:valuation.valuation_date,p_market_value:Number(valuation.market_value),p_cash_value:Number(valuation.cash_value||0),p_net_contributions:Number(valuation.net_contributions||0),p_net_withdrawals:Number(valuation.net_withdrawals||0),p_unrealized_pnl:Number(valuation.unrealized_pnl||0),p_realized_pnl:Number(valuation.realized_pnl||0),p_time_weighted_return:valuation.time_weighted_return===''?null:Number(valuation.time_weighted_return),p_money_weighted_return:valuation.money_weighted_return===''?null:Number(valuation.money_weighted_return)});if(error)throw error;setError('Valuation recorded.')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <section className="panel"><p className="eyebrow">Admin / Manager / Compliance Console</p><h1 className="title">Investment Management</h1><p className="lede">Portfolio governance, client operations, assets, corporate actions, valuation and reporting.</p>{error&&<div className="notice">{error}</div>}<div className="admin-tabs">{[['overview','Overview'],['portfolios','Portfolios'],['versions','Version Editor'],['assets','Assets'],['actions','Corporate Actions'],['clients','Clients'],['valuation','Valuation']].map(([k,v])=><button key={k} className={'btn btn-small '+(tab===k?'btn-primary':'btn-ghost')} onClick={()=>setTab(k)}>{v}</button>)}</div>
 {tab==='overview'&&<div className="admin-kpis"><div className="dash-stat-card"><b>{data.profiles.length}</b><span>Clients / Users</span></div><div className="dash-stat-card"><b>{data.requests.length}</b><span>Investment Requests</span></div><div className="dash-stat-card"><b>{data.portfolios.length}</b><span>Portfolios</span></div><div className="dash-stat-card"><b>{data.actions.filter((x:any)=>x.status==='pending_review').length}</b><span>Actions Awaiting Review</span></div></div>}
 {tab==='portfolios'&&<div className="admin-layout"><div className="dash-section"><h3>Create / Edit Portfolio</h3><input placeholder="Portfolio name" value={portfolio.name} onChange={e=>setPortfolio({...portfolio,name:e.target.value})}/><input placeholder="Unique slug" value={portfolio.slug} onChange={e=>setPortfolio({...portfolio,slug:e.target.value})}/><button className="btn btn-primary" disabled={busy||!portfolio.name||!portfolio.slug} onClick={savePortfolio}>Save portfolio</button></div><div className="dash-section full"><table className="admin-table"><thead><tr><th>Name</th><th>Slug</th><th>Active</th><th>Versions</th><th/></tr></thead><tbody>{data.portfolios.map((p:any)=><tr key={p.id}><td>{p.name}</td><td>{p.slug}</td><td>{p.active?'Yes':'No'}</td><td>{p.portfolio_versions?.length||0}</td><td><button className="link" onClick={()=>setPortfolio({id:p.id,name:p.name,slug:p.slug,active:p.active})}>Edit</button></td></tr>)}</tbody></table></div></div>}
 {tab==='versions'&&<div className="admin-layout"><div className="dash-section"><h3>Portfolio Version Editor</h3><select value={version.portfolio_id} onChange={e=>setVersion({...version,portfolio_id:e.target.value})}><option value="">Select portfolio</option>{data.portfolios.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="number" placeholder="Version" value={version.version} onChange={e=>setVersion({...version,version:e.target.value})}/><select value={version.band} onChange={e=>setVersion({...version,band:e.target.value})}><option>Conservative</option><option>Balanced</option><option>Aggressive</option></select><input placeholder="Target return decimal" value={version.target_return} onChange={e=>setVersion({...version,target_return:e.target.value})}/><input placeholder="Volatility decimal" value={version.volatility} onChange={e=>setVersion({...version,volatility:e.target.value})}/><input type="number" placeholder="Risk score" value={version.risk_score} onChange={e=>setVersion({...version,risk_score:e.target.value})}/><textarea placeholder="Strategy description" value={version.definition.description} onChange={e=>setVersion({...version,definition:{description:e.target.value}})}/><button className="btn btn-primary" disabled={busy||!version.portfolio_id} onClick={saveVersion}>Save draft version</button></div><div className="dash-section full"><h3>Maker-checker workflow</h3><div className="maker-checker-flow"><div className="mc-step active">Draft</div><span className="mc-arrow">→</span><div className="mc-step pending">Investment Review</div><span className="mc-arrow">→</span><div className="mc-step pending">Compliance Approval</div><span className="mc-arrow">→</span><div className="mc-step pending">Published</div></div></div></div>}
 {tab==='assets'&&<div className="admin-layout"><div className="dash-section"><h3>Asset Master</h3>{[['symbol','Symbol'],['name','Name'],['asset_class','Asset Class'],['currency','Currency'],['exchange','Exchange'],['isin','ISIN']].map(([k,l])=><input key={k} placeholder={l} value={asset[k]||''} onChange={e=>setAsset({...asset,[k]:e.target.value})}/>)}<button className="btn btn-primary" onClick={saveAsset}>Save asset</button></div><div className="dash-section full"><table className="admin-table"><thead><tr><th>Symbol</th><th>Name</th><th>Class</th><th>Active</th></tr></thead><tbody>{data.assets.map((a:any)=><tr key={a.id}><td>{a.symbol}</td><td>{a.name}</td><td>{a.asset_class}</td><td>{a.active?'Yes':'No'}</td></tr>)}</tbody></table></div></div>}
 {tab==='actions'&&<div className="admin-layout"><div className="dash-section"><h3>Corporate Actions</h3><select value={action.asset_id} onChange={e=>setAction({...action,asset_id:e.target.value})}><option value="">Select asset</option>{data.assets.map((a:any)=><option key={a.id} value={a.id}>{a.symbol} · {a.name}</option>)}</select><select value={action.action_type} onChange={e=>setAction({...action,action_type:e.target.value})}>{['dividend','split','merger','rights_issue','tender_offer','redemption','name_change','symbol_change','other'].map(x=><option key={x}>{x}</option>)}</select><button className="btn btn-primary" onClick={saveAction}>Create action</button><table className="admin-table"><tbody>{data.actions.map((a:any)=><tr key={a.id}><td>{a.assets?.symbol}</td><td>{a.action_type}</td><td>{a.ex_date||'-'}</td><td>{a.status}</td></tr>)}</tbody></table></div></div>}
 {tab==='clients'&&<div className="dash-section full"><h3>Investment Clients</h3><table className="admin-table"><tbody>{data.profiles.map((p:any)=>{const rs=data.requests.filter((r:any)=>r.user_id===p.id);return <tr key={p.id}><td>{p.display_name||p.id}</td><td>{p.role}</td><td>{rs.length}</td><td>{rs[0]?.status||'No requests'}</td></tr>})}</tbody></table></div>}
 {tab==='valuation'&&<div className="admin-layout"><div className="dash-section"><h3>Daily Valuation</h3>{['user_id','portfolio_version_id','valuation_date','market_value','cash_value','net_contributions','net_withdrawals','unrealized_pnl','realized_pnl','time_weighted_return','money_weighted_return'].map(k=><input key={k} placeholder={k} value={valuation[k]??''} onChange={e=>setValuation({...valuation,[k]:e.target.value})}/>)}<button className="btn btn-primary" disabled={busy} onClick={recordValuation}>Record valuation</button></div></div>}
 </section>
}


function Root(){const[session,setSession]=useState<SessionState>(null),[loading,setLoading]=useState(true);useEffect(()=>{let mounted=true;(async()=>{try{if(supabase&&mounted)setSession(await getCurrentProfile())}finally{if(mounted)setLoading(false)}})();const sub=supabase?.auth.onAuthStateChange(()=>{getCurrentProfile().then(s=>mounted&&setSession(s)).catch(()=>mounted&&setSession(null))});return()=>{mounted=false;sub?.data.subscription.unsubscribe()}},[]);if(loading)return <div className="center">Starting Guided Portfolios...</div>;if(!session)return <Auth onDone={setSession}/>;if(session.profile.role) (window as any).__emcoinRole=session.profile.role; return <App session={session} onLogout={async()=>{await signOut();setSession(null)}}/>}
createRoot(document.getElementById('root')!).render(<Root/>);
