-- Operations ledger, reconciliation, drift, rebalance, performance and market data
-- Applied to production Supabase project cpzsciqyrhgbczveqxyp
create table if not exists public.transaction_ledger (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete restrict,portfolio_version_id uuid references public.portfolio_versions(id) on delete restrict,asset_id uuid references public.assets(id) on delete restrict,transaction_type text not null check (transaction_type in ('subscription','redemption','buy','sell','dividend','fee','tax','transfer_in','transfer_out','corporate_action','adjustment')),trade_date date not null,settlement_date date,quantity numeric,price numeric,gross_amount numeric not null default 0,fees numeric not null default 0,taxes numeric not null default 0,net_amount numeric not null default 0,currency text not null default 'AED',external_reference text,status text not null default 'posted' check(status in ('pending','posted','reversed')),source text not null default 'manual',metadata jsonb not null default '{}'::jsonb,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create index if not exists idx_transaction_ledger_user_date on public.transaction_ledger(user_id,trade_date desc);
create index if not exists idx_transaction_ledger_portfolio_date on public.transaction_ledger(portfolio_version_id,trade_date desc);
create unique index if not exists uq_transaction_external_reference on public.transaction_ledger(external_reference) where external_reference is not null;
create table if not exists public.reconciliation_runs (id uuid primary key default gen_random_uuid(),run_date date not null,source text not null,status text not null default 'pending' check(status in ('pending','matched','exception','approved')),total_records integer not null default 0,matched_records integer not null default 0,exception_records integer not null default 0,total_amount numeric not null default 0,variance_amount numeric not null default 0,notes text,created_by uuid references public.profiles(id),approved_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.reconciliation_items (id uuid primary key default gen_random_uuid(),run_id uuid not null references public.reconciliation_runs(id) on delete cascade,transaction_id uuid references public.transaction_ledger(id),external_reference text,expected_amount numeric not null default 0,actual_amount numeric not null default 0,variance_amount numeric not null default 0,status text not null default 'exception' check(status in ('matched','exception','resolved')),resolution text,resolved_by uuid references public.profiles(id),resolved_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.portfolio_drift_alerts (id uuid primary key default gen_random_uuid(),portfolio_version_id uuid not null references public.portfolio_versions(id) on delete restrict,asset_id uuid references public.assets(id) on delete restrict,as_of_date date not null,target_weight numeric not null,actual_weight numeric not null,drift numeric not null,threshold numeric not null,status text not null default 'open' check(status in ('open','acknowledged','rebalance_pending','resolved')),created_at timestamptz not null default now(),resolved_at timestamptz);
create index if not exists idx_drift_open on public.portfolio_drift_alerts(status,as_of_date desc);
create table if not exists public.rebalance_orders (id uuid primary key default gen_random_uuid(),portfolio_version_id uuid not null references public.portfolio_versions(id) on delete restrict,asset_id uuid references public.assets(id) on delete restrict,side text not null check(side in ('buy','sell')),target_weight numeric not null,current_weight numeric not null,quantity numeric,estimated_value numeric,status text not null default 'draft' check(status in ('draft','pending_approval','approved','submitted','executed','cancelled')),reason text,created_by uuid references public.profiles(id),approved_by uuid references public.profiles(id),executed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.performance_snapshots (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete restrict,portfolio_version_id uuid not null references public.portfolio_versions(id) on delete restrict,as_of_date date not null,beginning_value numeric not null default 0,ending_value numeric not null default 0,net_cash_flow numeric not null default 0,twr numeric,mwr numeric,benchmark_return numeric,alpha numeric,created_at timestamptz not null default now(),unique(user_id,portfolio_version_id,as_of_date));
create table if not exists public.market_prices (id uuid primary key default gen_random_uuid(),asset_id uuid not null references public.assets(id) on delete restrict,price_date date not null,close_price numeric not null,currency text not null default 'AED',source text not null,source_reference text,created_at timestamptz not null default now(),unique(asset_id,price_date,source));
create index if not exists idx_market_prices_asset_date on public.market_prices(asset_id,price_date desc);
create table if not exists public.document_events (id uuid primary key default gen_random_uuid(),document_id uuid not null references public.documents(id) on delete cascade,event_type text not null check(event_type in ('created','generated','signed','downloaded','archived','revoked')),actor_id uuid references public.profiles(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.compliance_cases (id uuid primary key default gen_random_uuid(),case_type text not null check(case_type in ('suitability','risk_breach','transaction','reconciliation','document','drift','corporate_action','other')),user_id uuid references public.profiles(id),severity text not null default 'medium' check(severity in ('low','medium','high','critical')),status text not null default 'open' check(status in ('open','investigating','remediated','closed')),title text not null,description text,due_at timestamptz,assigned_to uuid references public.profiles(id),resolved_by uuid references public.profiles(id),resolved_at timestamptz,created_at timestamptz not null default now());
alter table public.transaction_ledger enable row level security; alter table public.reconciliation_runs enable row level security; alter table public.reconciliation_items enable row level security; alter table public.portfolio_drift_alerts enable row level security; alter table public.rebalance_orders enable row level security; alter table public.performance_snapshots enable row level security; alter table public.market_prices enable row level security; alter table public.document_events enable row level security; alter table public.compliance_cases enable row level security;
create policy "ledger owner read" on public.transaction_ledger for select to authenticated using ((select auth.uid())=user_id or (select public.is_staff()));
create policy "reconciliation staff" on public.reconciliation_runs for select to authenticated using ((select public.is_staff()));
create policy "reconciliation items staff" on public.reconciliation_items for select to authenticated using ((select public.is_staff()));
create policy "drift staff" on public.portfolio_drift_alerts for select to authenticated using ((select public.is_staff()));
create policy "rebalance staff" on public.rebalance_orders for select to authenticated using ((select public.is_staff()));
create policy "performance owner read" on public.performance_snapshots for select to authenticated using ((select auth.uid())=user_id or (select public.is_staff()));
create policy "market prices auth read" on public.market_prices for select to authenticated using (true);
create policy "document events owner read" on public.document_events for select to authenticated using (exists(select 1 from public.documents d where d.id=document_id and (d.user_id=(select auth.uid()) or (select public.is_staff()))));
create policy "compliance staff" on public.compliance_cases for select to authenticated using ((select public.is_staff()));
