revoke execute on function public.admin_delete_asset(uuid) from public, anon;
revoke execute on function public.admin_delete_corporate_action(uuid) from public, anon;
revoke execute on function public.admin_delete_portfolio(uuid) from public, anon;
revoke execute on function public.admin_record_valuation(uuid,uuid,date,numeric,numeric,numeric,numeric,numeric,numeric,numeric) from public, anon;
revoke execute on function public.admin_set_corporate_action_status(uuid,public.corporate_action_status) from public, anon;
revoke execute on function public.admin_upsert_asset(uuid,text,text,text,text,text,text,boolean,jsonb) from public, anon;
revoke execute on function public.admin_upsert_corporate_action(uuid,uuid,text,date,date,date,date,numeric,numeric,text,jsonb) from public, anon;
revoke execute on function public.admin_upsert_portfolio(uuid,text,text,boolean) from public, anon;
revoke execute on function public.admin_upsert_portfolio_version(uuid,uuid,integer,text,numeric,numeric,integer,jsonb) from public, anon;
revoke execute on function public.compliance_approve_portfolio_version(uuid,boolean,text) from public, anon;
revoke execute on function public.create_preference_assessment(jsonb) from public, anon;
revoke execute on function public.get_my_role() from public, anon;
revoke execute on function public.is_staff() from public, anon;
revoke execute on function public.record_investment_consent(uuid,text) from public, anon;
revoke execute on function public.review_portfolio_version(uuid,boolean,text) from public, anon;
revoke execute on function public.submit_investment_request(uuid,numeric,numeric,uuid) from public, anon;
revoke execute on function public.submit_portfolio_for_review(uuid) from public, anon;
grant execute on function public.compliance_approve_portfolio_version(uuid,boolean,text) to authenticated;
grant execute on function public.create_preference_assessment(jsonb) to authenticated;
grant execute on function public.get_my_role() to authenticated;
grant execute on function public.is_staff() to authenticated;
grant execute on function public.record_investment_consent(uuid,text) to authenticated;
grant execute on function public.review_portfolio_version(uuid,boolean,text) to authenticated;
grant execute on function public.submit_investment_request(uuid,numeric,numeric,uuid) to authenticated;
grant execute on function public.submit_portfolio_for_review(uuid) to authenticated;